application: ulapph-cloud-sca
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /products
  script: _go_app

- url: /cart
  script: _go_app

- url: /process
  script: _go_app

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.htm)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.htm)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
  
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /(.*\.yaml)
  mime_type: text/x-yaml
  static_files: static/\1
  upload: static/(.*\.yaml)

- url: /(.*\.json)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.json)

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: static/\1
  upload: static/(.*\.swf)
  
# audio files
- url: /(.*\.(wav|mp3))
  mime_type: audio/wav
  static_files: static/\1
  upload: static/(.*\.(wav|mp3))
  
# font files
- url: /(.*\.(woff|ttf|eot|svg))
  mime_type: font/opentype
  static_files: static/\1
  upload: static/(.*\.(woff|ttf|eot|svg))
  
# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|pdf))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|pdf))

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
